let candles=[];const $=id=>document.getElementById(id);window.LabData={get candles(){return LabEngine.normalize(candles)},get interval(){return $("interval").value},get symbol(){return $("symbol").value.toUpperCase()}};const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString("pt-BR",{maximumFractionDigits:d}):"—";
function parseCSV(t){const lines=t.trim().split(/\r?\n/),heads=lines.shift().split(",").map(x=>x.trim().toLowerCase());return lines.map(line=>{const v=line.split(",");return Object.fromEntries(heads.map((h,i)=>[h,v[i]]))})}
function sample(){let p=100,out=[];for(let i=0;i<60;i++){const box=i>30;const drift=box?(Math.sin(i)*.7):(i<20?1.1:-.25);const o=p,p=box?105+Math.sin(i*1.7)*2:p+drift;out.push({time:Date.now()-(60-i)*3600000,open:o,high:Math.max(o,p)+.6,low:Math.min(o,p)-.6,close:p,volume:900+((i*71)%300)})}const last=out.at(-1);last.close=109;last.high=109.5;last.volume=1900;return out}
function fact(k,v){return '<div class="fact"><span>'+k+'</span><strong>'+v+'</strong></div>'}
function renderHistory(){const h=JSON.parse(localStorage.getItem("labHistory")||"[]");$("history").innerHTML=h.map(x=>'<tr><td>'+x.date+'</td><td>'+x.symbol+'</td><td>'+x.interval+'</td><td>'+x.classification+'</td><td>'+x.score+'</td><td>'+x.box+'</td><td>'+x.obv+'</td></tr>').join("")||'<tr><td colspan="7">Nenhum resultado salvo.</td></tr>'}
function run(){try{const r=LabEngine.analyze(candles,+$("lookback").value);$("classification").textContent=r.classification.replaceAll("_"," ");$("score").textContent=r.score+"/100";$("boxState").textContent=r.box.state.replaceAll("_"," ");$("obvState").textContent=r.obv.trend;
$("technical").innerHTML=fact("Candles válidos",r.candles)+fact("Suporte",fmt(r.box.support))+fact("Resistência",fmt(r.box.resistance))+fact("Amplitude do caixote",fmt(r.box.rangePct)+"%")+fact("Toques topo/fundo",(r.box.topTouches||0)+" / "+(r.box.bottomTouches||0))+fact("OBV acumulado",fmt(r.obv.value,0))+fact("Inclinação OBV (10 candles)",fmt(r.obv.slope,0))+fact("Divergência OBV",r.obv.divergence)+fact("Bandeira",r.flag.state.replaceAll("_"," "));
$("reasons").innerHTML=fact("Conta como sinal?",r.countAsSignal?"SIM":"NÃO")+fact("Rompimento exige volume","≥ 1,20× média")+fact("Score mínimo","80")+fact("Neutro sem rompimento","EM OBSERVAÇÃO")+fact("Confirmação OBV","Obrigatória");
const h=JSON.parse(localStorage.getItem("labHistory")||"[]");h.unshift({date:new Date().toLocaleString("pt-BR"),symbol:$("symbol").value.toUpperCase(),interval:$("interval").value,classification:r.classification,score:r.score,box:r.box.state,obv:r.obv.trend});localStorage.setItem("labHistory",JSON.stringify(h.slice(0,100)));renderHistory();$("notice").textContent="Análise concluída localmente. Nenhum dado foi enviado a banco ou outro EP."}catch(e){$("notice").textContent=e.message}}
$("sample").onclick=()=>{candles=sample();$("notice").textContent=candles.length+" candles de exemplo carregados."};$("analyze").onclick=run;
$("file").onchange=async e=>{const f=e.target.files[0];if(!f)return;const t=await f.text();candles=f.name.endsWith(".json")?JSON.parse(t):parseCSV(t);$("notice").textContent=candles.length+" registros importados localmente."};
$("clear").onclick=()=>{localStorage.removeItem("labHistory");renderHistory()};renderHistory();