/* Isolated experimental EMA9 module. No Supabase or official motor writes. */
(function(root){
'use strict';
const MIN=60000,KEY='ep_oscillation_lab_v1',targets=[.5,1,2,3,5,10,20,30,50];
function ema(c){const a=[];c.forEach((x,i)=>a.push(i?a[i-1]+.2*(x.c-a[i-1]):x.c));return a;}
function prepare(c,variant){const e=ema(c),out=[];for(let i=10;i<c.length;i++){const prev=e[i-1]-e[i-2],now=e[i]-e[i-1];let d=0;if(variant==='CROSS'){if(prev<0&&c[i-1].c<=e[i-1]&&c[i].c>e[i])d=1;if(prev>0&&c[i-1].c>=e[i-1]&&c[i].c<e[i])d=-1;}else{if(prev<=0&&now>0)d=1;if(prev>=0&&now<0)d=-1;}out.push({t:c[i].end,candle:c[i],d,slope:now,close:c[i].c,ema:e[i]});}return out;}
function run(data,variant,tf,tick){
const base=prepare(data[tf],variant),context=data.h1,he=ema(context),events=[],trades=[];let bi=0,hi=-1,pending=null,active=null,lastSide=0;
const finish=(bar,price,reason,ambiguous=false)=>{const net=active.side*(price/active.entry-1)*100;active.exit=price;active.exitTime=bar.end;active.reason=reason;active.ambiguous=ambiguous;active.returnPct=net;active.status='CLOSED';trades.push(active);events.push({type:'EXIT',time:bar.end,reason});active=null;};
for(const bar of data.m1){
while(hi+1<context.length&&context[hi+1].end<=bar.t)hi++;
while(bi<base.length&&base[bi].t<=bar.t){const s=base[bi++];lastSide=s.slope>0?1:s.slope<0?-1:0;
if(pending&&lastSide!==pending.side){events.push({type:'CANCEL',time:s.t});pending=null;}
if(active&&((variant==='CROSS'&&active.side*(s.close-s.ema)<0)||(variant==='TURN'&&lastSide!==active.side))){finish({end:bar.t},bar.o,'STRUCTURE_CHANGE');}
if(s.d){pending={side:s.d,trigger:s.d>0?s.candle.h+tick:s.candle.l-tick,stop:s.d>0?s.candle.l-tick:s.candle.h+tick,preparedAt:s.t};events.push({type:'ALERT',time:s.t,side:s.d});}}
if(active){const stopHit=active.side>0?bar.l<=active.stop:bar.h>=active.stop;if(stopHit){const price=active.side>0?Math.min(bar.o,active.stop):Math.max(bar.o,active.stop);finish(bar,price,'STOP');continue;}active.mfe=Math.max(active.mfe,active.side>0?(bar.h/active.entry-1)*100:(1-bar.l/active.entry)*100);active.mae=Math.min(active.mae,active.side>0?(bar.l/active.entry-1)*100:(1-bar.h/active.entry)*100);for(const t of targets)if(active.mfe>=t&&!active.targetTimes[t])active.targetTimes[t]=bar.end;}
if(!active&&pending&&hi>=10){const hit=pending.side>0?bar.h>=pending.trigger:bar.l<=pending.trigger;if(hit){const side=pending.side,entry=side>0?Math.max(bar.o,pending.trigger):Math.min(bar.o,pending.trigger);const ctx=he[hi]>he[hi-1]?1:he[hi]<he[hi-1]?-1:0;active={id:[variant,tf,bar.t,side].join('|'),variant,tf,side,entry,stop:pending.stop,entryTime:bar.t,preparedAt:pending.preparedAt,h1Direction:ctx,alignedH1:ctx===side,status:'OPEN',mfe:0,mae:0,targetTimes:{}};events.push({type:'ENTRY',time:bar.t,side});pending=null;const collision=side>0?bar.l<=active.stop:bar.h>=active.stop;if(collision){finish(bar,active.stop,'ENTRY_STOP_SAME_M1',true);}/* Entry minute excursion excluded: intrabar ordering unknown. */}}
}
if(active)trades.push(active);
const closed=trades.filter(t=>t.status==='CLOSED'&&!t.ambiguous),hits=Object.fromEntries(targets.map(t=>[t,trades.filter(x=>!x.ambiguous&&x.mfe>=t).length]));
return {variant,tf,trades,events,summary:{signals:trades.length,alerts:events.filter(x=>x.type==='ALERT').length,closed:closed.length,open:trades.filter(x=>x.status==='OPEN').length,ambiguous:trades.filter(x=>x.ambiguous).length,winners:closed.filter(x=>x.returnPct>0).length,avgReturnPct:closed.length?closed.reduce((s,x)=>s+x.returnPct,0)/closed.length:null,hits}};
}
const api={ema,prepare,run,targets};if(typeof module!=='undefined')module.exports=api;if(!root)return;root.EPOscillationLab=api;
let reports=[],timer=null,busy=false,identity='';
/* Legacy candle cache was too large for localStorage. Remove only that obsolete cache; test snapshots remain untouched. */
try{localStorage.removeItem(KEY+'_candles');}catch(_){}
const $=id=>document.getElementById(id),fmt=x=>x==null?'—':Number(x).toFixed(2);
const DB_NAME='ep_oscillation_lab_v1_db',STORE='cache',CACHE_ID='candles';
function openDB(){return new Promise((resolve,reject)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE);};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}
async function loadCandleCache(){try{const db=await openDB();const v=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),q=tx.objectStore(STORE).get(CACHE_ID);q.onsuccess=()=>resolve(q.result||{});q.onerror=()=>reject(q.error);});db.close();return v;}catch(e){return {};}}
async function saveCandleCache(value){const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,CACHE_ID);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();}

async function candles(symbol,interval){let error;for(const host of ['https://data-api.binance.vision','https://api.binance.com']){try{const r=await fetch(`${host}/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${interval}&limit=1000`);if(!r.ok)throw Error(`HTTP ${r.status}`);const j=await r.json();return j.map(x=>({t:+x[0],end:+x[6]+1,o:+x[1],h:+x[2],l:+x[3],c:+x[4]})).filter(x=>x.end<=Date.now());}catch(e){error=e;}}throw error;}
async function tickSize(symbol){const r=await fetch(`https://data-api.binance.vision/api/v3/exchangeInfo?symbol=${encodeURIComponent(symbol)}`);if(!r.ok)throw Error('Não foi possível obter o tick real');const j=await r.json();const tick=Number(j.symbols?.[0]?.filters?.find(x=>x.filterType==='PRICE_FILTER')?.tickSize);if(!(tick>0))throw Error('Tick inválido');return tick;}
function render(){ $('oscOutput').innerHTML=reports.map(r=>`<h3>${r.variant==='CROSS'?'Teste A — Cruzamento do preço':'Teste B — Virada da MME9'} · ${r.tf.toUpperCase()}</h3><p>${r.summary.signals} entradas · ${r.summary.open} abertas · ${r.summary.ambiguous} ambíguas · retorno médio fechado bruto ${fmt(r.summary.avgReturnPct)}%</p><p>${targets.map(t=>`≥${t}%: ${r.summary.hits[t]}`).join(' · ')}</p><div class="table-wrap"><table><tr><th>Direção</th><th>Entrada</th><th>Stop</th><th>H1 alinhado</th><th>MFE</th><th>MAE</th><th>Retorno saída</th><th>Estado</th></tr>${r.trades.slice(-15).reverse().map(t=>`<tr><td>${t.side>0?'COMPRA':'VENDA'}</td><td>${t.entry}</td><td>${t.stop}</td><td>${t.alignedH1?'SIM':'NÃO'}</td><td>${fmt(t.mfe)}%</td><td>${fmt(t.mae)}%</td><td>${fmt(t.returnPct)}%</td><td>${t.reason||t.status}</td></tr>`).join('')}</table></div>`).join('');}
async function execute(){if(busy)return;busy=true;$('oscStatus').textContent='Carregando candles fechados e tick real...';const symbol=$('oscSymbol').value.trim().toUpperCase();try{const [m1,m5,m15,h1,tick]=await Promise.all([candles(symbol,'1m'),candles(symbol,'5m'),candles(symbol,'15m'),candles(symbol,'1h'),tickSize(symbol)]);const cacheKey=KEY+'_candles';const cache=await loadCandleCache();const data={m1,m5,m15,h1};if(cache.symbol===symbol){for(const tf of ['m1','m5','m15','h1'])data[tf]=[...new Map([...(cache.data?.[tf]||[]),...data[tf]].map(c=>[c.t,c])).values()].sort((a,b)=>a.t-b.t).slice(-10000);}await saveCandleCache({symbol,data});try{localStorage.removeItem(cacheKey);}catch(_){}reports=['CROSS','TURN'].flatMap(v=>['m5','m15'].map(tf=>run(data,v,tf,tick)));const result={version:1,symbol,generatedAt:new Date().toISOString(),windowStart:data.m1[0]?.t,windowEnd:data.m1.at(-1)?.end,tick,reports,note:'Spot Binance. Venda é hipótese direcional; sem execução de ordens. Custos não incluídos. H1 informativo, não bloqueia entradas. Entrada/stop na mesma vela M1 é ambígua.'};
const stored=JSON.parse(localStorage.getItem(KEY)||'{"snapshots":[]}');stored.snapshots=(stored.snapshots||[]).filter(x=>x.symbol!==symbol).concat(result).slice(-25);localStorage.setItem(KEY,JSON.stringify(stored));render();identity=symbol;$('oscStatus').textContent=`${symbol} · ${m1.length} minutos fechados · ${new Date().toLocaleTimeString()} · primeira coleta de cerca de 16h40; histórico acumulado até 10.000 minutos. Resultados A/B separados.`;
}catch(e){$('oscStatus').textContent=`Falha: ${e.message}`;}finally{busy=false;}}
function init(){const main=document.querySelector('main');if(!main)return;const s=document.createElement('section');s.className='panel';s.id='oscillationLab';s.innerHTML='<h2>OSCILAÇÕES — MME9 · testes A/B separados</h2><p>H1 contexto · M5/M15 preparação · M1 gatilho. Candles fechados, sem ordens e sem conexão com motores oficiais. B3 não incluída: a fonte atual não garante M1.</p><input id="oscSymbol" value="BTCUSDT" maxlength="20"><button id="oscRun">Executar ambos os testes</button><button id="oscTrack">Iniciar acompanhamento (60s)</button><button id="oscExport">Baixar JSON A/B</button><p id="oscStatus">Aguardando execução. Acompanhamento funciona somente com esta página aberta.</p><p>Saídas: A por fechamento contrário à MME9; B por virada contrária da média. Stop fixado no candle gatilho. Ganhos pequenos são registrados; não há alvo obrigatório de 10% ou 50%. MFE/MAE são conservadores e excluem o minuto de entrada e o minuto do stop.</p><div id="oscOutput"></div>';main.appendChild(s);$('oscRun').onclick=execute;$('oscTrack').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('oscTrack').textContent='Iniciar acompanhamento (60s)';return;}execute();timer=setInterval(execute,60000);$('oscTrack').textContent='Parar acompanhamento';};$('oscExport').onclick=()=>{const text=localStorage.getItem(KEY);if(!text){$('oscStatus').textContent='Execute os testes primeiro.';return;}const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ep-oscilacoes-mme9-testes-ab.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(typeof window!=='undefined'?window:null);
