/* Fluxo Institucional / Tape Reading Experimental. SOMENTE INFORMATIVO: nao altera score, classificacao, gate ou sinais. */
(function(global){
  const UNIVERSE=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','ADAUSDT','DOGEUSDT','AVAXUSDT','LINKUSDT','DOTUSDT','TRXUSDT','LTCUSDT','BCHUSDT','XLMUSDT','UNIUSDT','ATOMUSDT','ETCUSDT','NEARUSDT','APTUSDT','FILUSDT','ICPUSDT','ARBUSDT','OPUSDT','SUIUSDT','AAVEUSDT'];
  const states=new Map(), sockets=new Map();
  const WINDOW_MS=60000, SPEED_MS=30000, BATCH_SIZE=8, ROTATE_MS=20000, DISPLAY_MS=8000;
  let batchStart=0,currentBatch=[],displayIndex=0,rotateTimer=null,displayTimer=null,pinnedSymbol='BTCUSDT';
  const now=()=>Date.now();
  const esc=s=>String(s??'—').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
  function state(symbol){if(!states.has(symbol))states.set(symbol,{symbol,market:'CRIPTO',bookImbalance:null,buyNotional:0,sellNotional:0,trades:[],largeTrades:[],speed:0,persistence:'AGUARDANDO',aggression:'AGUARDANDO',connected:false,updatedAt:null});return states.get(symbol)}
  function trim(s){const t=now();s.trades=s.trades.filter(x=>t-x.t<=WINDOW_MS);s.largeTrades=s.largeTrades.filter(x=>t-x.t<=WINDOW_MS);}
  function recalc(s){trim(s);const t=now(),recent=s.trades.filter(x=>t-x.t<=SPEED_MS);s.speed=recent.length/(SPEED_MS/1000);s.buyNotional=s.trades.filter(x=>x.side==='BUY').reduce((a,x)=>a+x.notional,0);s.sellNotional=s.trades.filter(x=>x.side==='SELL').reduce((a,x)=>a+x.notional,0);const total=s.buyNotional+s.sellNotional,imb=total?(s.buyNotional-s.sellNotional)/total:0;s.aggression=Math.abs(imb)<.08?'NEUTRA':imb>0?'COMPRADORA':'VENDEDORA';const buckets=[0,1,2].map(i=>{const a=t-(3-i)*20000,b=t-(2-i)*20000,rows=s.trades.filter(x=>x.t>=a&&x.t<b),buy=rows.filter(x=>x.side==='BUY').reduce((z,x)=>z+x.notional,0),sell=rows.filter(x=>x.side==='SELL').reduce((z,x)=>z+x.notional,0),v=buy+sell?(buy-sell)/(buy+sell):0;return v});if(buckets.every(v=>v>.10))s.persistence='COMPRA PERSISTENTE';else if(buckets.every(v=>v<-.10))s.persistence='VENDA PERSISTENTE';else s.persistence='SEM PERSISTENCIA';s.updatedAt=t;render();global.dispatchEvent(new CustomEvent('lab-tape-updated',{detail:{symbol:s.symbol}}));}
  function onDepth(symbol,d){const s=state(symbol),bids=d.bids||d.b||[],asks=d.asks||d.a||[],b=bids.reduce((z,x)=>z+(+x[1]||0),0),a=asks.reduce((z,x)=>z+(+x[1]||0),0);s.bookImbalance=b+a?(b-a)/(b+a):null;s.connected=true;s.updatedAt=now();render();}
  function onTrade(symbol,d){const s=state(symbol),price=+(d.p??d.price),qty=+(d.q??d.quantity),notional=price*qty,side=d.m?'SELL':'BUY',row={t:+d.T||now(),side,notional,price,qty};s.trades.push(row);const notionals=s.trades.slice(-100).map(x=>x.notional).sort((a,b)=>a-b),median=notionals.length?notionals[Math.floor(notionals.length/2)]:0,threshold=Math.max(50000,median*5);if(notional>=threshold)s.largeTrades.push({...row,threshold});s.connected=true;recalc(s);}
  function connect(symbol){symbol=String(symbol||'').toUpperCase();if(!symbol.endsWith('USDT')||sockets.has(symbol))return;const streams=`${symbol.toLowerCase()}@depth10@100ms/${symbol.toLowerCase()}@aggTrade`,url=`wss://data-stream.binance.vision/stream?streams=${streams}`;let ws;try{ws=new WebSocket(url)}catch{return}sockets.set(symbol,ws);ws.onopen=()=>{const s=state(symbol);s.connected=true;render()};ws.onmessage=e=>{try{const j=JSON.parse(e.data),d=j.data||j,name=j.stream||'';if(name.includes('@depth'))onDepth(symbol,d);else if(name.includes('@aggTrade'))onTrade(symbol,d)}catch{}};ws.onclose=()=>{sockets.delete(symbol);const s=state(symbol);s.connected=false;render()};ws.onerror=()=>{const s=state(symbol);s.connected=false;render()};}
  function disconnect(symbol){const ws=sockets.get(symbol);if(!ws)return;sockets.delete(symbol);try{ws.onclose=null;ws.close()}catch{}const s=state(symbol);s.connected=false;}
  function nextBatch(){const base=[];for(let i=0;i<BATCH_SIZE-1;i++)base.push(UNIVERSE[(batchStart+i)%UNIVERSE.length]);batchStart=(batchStart+BATCH_SIZE-1)%UNIVERSE.length;currentBatch=[pinnedSymbol,...base.filter(x=>x!==pinnedSymbol)].slice(0,BATCH_SIZE);for(const symbol of [...sockets.keys()])if(!currentBatch.includes(symbol))disconnect(symbol);currentBatch.forEach(connect);displayIndex=0;render();}
  function startRotation(){if(rotateTimer)return;nextBatch();rotateTimer=setInterval(nextBatch,ROTATE_MS);displayTimer=setInterval(()=>{if(currentBatch.length){displayIndex=(displayIndex+1)%currentBatch.length;render()}},DISPLAY_MS)}
  function watch(symbol){symbol=String(symbol||'').toUpperCase();if(symbol.endsWith('USDT')){pinnedSymbol=symbol;connect(symbol);render()}}
  function watchMany(symbols){const first=(symbols||[]).map(x=>String(x||'').toUpperCase()).find(x=>x.endsWith('USDT'));if(first)watch(first);startRotation()}
  function get(symbol,market){if(String(market||'').toUpperCase()==='B3')return {available:false,label:'B3 SEM BOOK/TAPE NA FONTE ATUAL'};const s=states.get(String(symbol||'').toUpperCase());if(!s)return {available:false,label:'AGUARDANDO FLUXO'};const bi=s.bookImbalance;return {...s,available:true,label:`${s.aggression} · Book ${bi==null?'—':(bi>=0?'+':'')+(bi*100).toFixed(0)+'%'} · ${s.speed.toFixed(1)} t/s`}}
  function render(){const symbol=currentBatch[displayIndex]||pinnedSymbol||'BTCUSDT',s=state(symbol),set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('tapeSymbol',`${symbol} · rotação AUTO`);set('tapeConnection',s.connected?'AO VIVO':'CONECTANDO');set('tapeBook',s.bookImbalance==null?'—':`${s.bookImbalance>=0?'+':''}${(s.bookImbalance*100).toFixed(1)}%`);const total=s.buyNotional+s.sellNotional,ag=total?100*(s.buyNotional-s.sellNotional)/total:0;set('tapeAggression',`${s.aggression} ${ag>=0?'+':''}${ag.toFixed(1)}%`);const last=s.largeTrades.at(-1);set('tapeLarge',`${s.largeTrades.length}/60s${last?' · '+last.side+' $'+Math.round(last.notional).toLocaleString('pt-BR'):''}`);set('tapeSpeed',`${s.speed.toFixed(2)} negócios/s`);set('tapePersistence',s.persistence)}
  document.addEventListener('DOMContentLoaded',()=>{const input=document.getElementById('symbol');pinnedSymbol=String(input?.value||'BTCUSDT').toUpperCase();input?.addEventListener('change',()=>{watch(input.value)});startRotation();render()});
  global.TapeReadingExperimental={get,watch,watchMany,render,startRotation,universe:UNIVERSE};
})(window);
