import fs from 'node:fs';
import path from 'node:path';

const CRYPTO=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','ADAUSDT','DOGEUSDT','AVAXUSDT','LINKUSDT','DOTUSDT','TRXUSDT','LTCUSDT','BCHUSDT','XLMUSDT','UNIUSDT','ATOMUSDT','ETCUSDT','NEARUSDT','APTUSDT','FILUSDT','ICPUSDT','ARBUSDT','OPUSDT','SUIUSDT','AAVEUSDT'];
const B3=['PETR4','VALE3','ITUB4','BBDC4','BBAS3','WEGE3','ABEV3','B3SA3','RENT3','SUZB3','PRIO3','ELET3','EQTL3','RADL3','GGBR4','CSNA3','MGLU3','LREN3','JBSS3','EMBR3'];
const TARGETS=[5,10,20,30,50];
const OUT=path.resolve('data/auto-signals.json');
const avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

function normalize(rows){return rows.map((r,i)=>({time:r.time??r.timestamp??i,open:+r.open,high:+r.high,low:+r.low,close:+r.close,volume:+r.volume})).filter(c=>[c.open,c.high,c.low,c.close,c.volume].every(Number.isFinite)&&c.high>=c.low&&c.volume>=0)}
function tr(c,p){return Math.max(c.high-c.low,Math.abs(c.high-p.close),Math.abs(c.low-p.close))}
function atr(c,n=14){if(c.length<2)return 0;return avg(c.slice(-n).map((x,i,a)=>tr(x,i?a[i-1]:c[Math.max(0,c.length-n-1)])))}
function obv(c){let value=0,series=[0];for(let i=1;i<c.length;i++){if(c[i].close>c[i-1].close)value+=c[i].volume;else if(c[i].close<c[i-1].close)value-=c[i].volume;series.push(value)}const n=Math.min(10,series.length-1),slope=n?series.at(-1)-series.at(-1-n):0,priceSlope=n?c.at(-1).close-c.at(-1-n).close:0;return {value,slope,trend:slope>0?'SUBINDO':slope<0?'CAINDO':'LATERAL',divergence:priceSlope<0&&slope>0?'ALTA':priceSlope>0&&slope<0?'BAIXA':'NENHUMA'}}
function box(c,lookback=20){const w=c.slice(-lookback-1,-1);if(w.length<lookback)return {state:'DADOS_INSUFICIENTES'};const resistance=Math.max(...w.map(x=>x.high)),support=Math.min(...w.map(x=>x.low)),mid=(resistance+support)/2,rangePct=mid?100*(resistance-support)/mid:Infinity,tol=(resistance-support)*.12;const topTouches=w.filter(x=>x.high>=resistance-tol).length,bottomTouches=w.filter(x=>x.low<=support+tol).length,a=atr(c),last=c.at(-1),volBase=avg(w.slice(-10).map(x=>x.volume)),volumeRatio=volBase?last.volume/volBase:0,compression=rangePct<=8&&topTouches>=2&&bottomTouches>=2,up=compression&&last.close>resistance+.15*a&&volumeRatio>=1.2,down=compression&&last.close<support-.15*a&&volumeRatio>=1.2;return {state:up?'ROMPIMENTO_ALTA':down?'ROMPIMENTO_BAIXA':compression?'DENTRO_DO_CAIXOTE':'SEM_CAIXOTE',volumeRatio}}
function flag(c){if(c.length<26)return {state:'DADOS_INSUFICIENTES'};const pole=c.slice(-26,-14),f=c.slice(-14,-1),last=c.at(-1),start=pole[0].close,end=pole.at(-1).close,impulse=100*(end-start)/start,high=Math.max(...f.map(x=>x.high)),low=Math.min(...f.map(x=>x.low)),retracement=Math.abs(end-last.close)/Math.max(Math.abs(end-start),1e-9),volumeRatio=last.volume/Math.max(avg(f.map(x=>x.volume)),1),bull=impulse>=6&&retracement<=.5,bear=impulse<=-6&&retracement<=.5,breakUp=bull&&last.close>high&&volumeRatio>=1.2,breakDown=bear&&last.close<low&&volumeRatio>=1.2;return {state:breakUp?'ROMPIMENTO_ALTA':breakDown?'ROMPIMENTO_BAIXA':bull||bear?'AGUARDANDO_ROMPIMENTO':'SEM_BANDEIRA',volumeRatio}}
function analyze(rows){const c=normalize(rows);if(c.length<96)throw Error('menos de 96 candles');const b=box(c),o=obv(c),f=flag(c),up=b.state==='ROMPIMENTO_ALTA'||f.state==='ROMPIMENTO_ALTA',down=b.state==='ROMPIMENTO_BAIXA'||f.state==='ROMPIMENTO_BAIXA',confirm=up?o.trend==='SUBINDO':down?o.trend==='CAINDO':false;let score=0;if(up||down)score+=55;if(confirm)score+=25;const vr=Math.max(b.volumeRatio||0,f.volumeRatio||0);if(vr>=1.5)score+=20;else if(vr>=1.2)score+=10;score=clamp(score,0,100);return {candles:c,box:b,obv:o,flag:f,score,classification:(up||down)&&confirm&&score>=80?(up?'SINAL_COMPRA':'SINAL_VENDA'):'SEM_SINAL'}}
async function binance(symbol){const r=await fetch(`https://api.binance.com/api/v3/klines?symbol=${symbol}&interval=1h&limit=120`);if(!r.ok)throw Error(`Binance ${r.status}`);const j=await r.json();return j.map(x=>({time:x[0],open:x[1],high:x[2],low:x[3],close:x[4],volume:x[5]}))}
async function yahoo(symbol){const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol+'.SA')}?range=1mo&interval=1h&includePrePost=false&events=div%2Csplits`;const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error(`Yahoo ${r.status}`);const d=(await r.json()).chart?.result?.[0];if(!d)throw Error('sem dados Yahoo');const q=d.indicators?.quote?.[0],t=d.timestamp||[];return t.map((ts,i)=>({time:ts*1000,open:q.open[i],high:q.high[i],low:q.low[i],close:q.close[i],volume:q.volume[i]})).filter(x=>[x.open,x.high,x.low,x.close,x.volume].every(Number.isFinite))}
const pct=(entry,v)=>entry?((v-entry)/entry)*100:0;
function load(){try{return JSON.parse(fs.readFileSync(OUT,'utf8'))}catch{return {signals:[]}}}
function updateTracking(signals,symbol,candles){if(!candles.length)return;for(const s of signals){if(s.symbol!==symbol)continue;const after=candles.filter(c=>c.time>=s.entryTime);if(!after.length)continue;const hi=Math.max(...after.map(c=>c.high)),lo=Math.min(...after.map(c=>c.low));const fav=s.direction==='COMPRA'?pct(s.entry,hi):-pct(s.entry,lo),adv=s.direction==='COMPRA'?pct(s.entry,lo):-pct(s.entry,hi);s.best=Math.max(s.best||0,fav);s.worst=Math.min(s.worst||0,adv);s.lastPrice=after.at(-1).close;s.targets=s.targets||{};for(const t of TARGETS)if(s.best>=t)s.targets[t]=true}}
async function main(){const prev=load(),signals=Array.isArray(prev.signals)?prev.signals:[],stats={crypto:{ok:0,error:0},b3:{ok:0,error:0}};for(const [market,list,fetcher] of [['CRIPTO',CRYPTO,binance],['B3',B3,yahoo]]){for(const symbol of list){try{const candles=await fetcher(symbol);const r=analyze(candles);updateTracking(signals,symbol,r.candles);if(r.classification.startsWith('SINAL_')){const last=r.candles.at(-1),direction=r.classification==='SINAL_COMPRA'?'COMPRA':'VENDA',id=`${market}|${symbol}|${last.time}|${direction}`;if(!signals.some(s=>s.id===id))signals.unshift({id,market,symbol,interval:'1h',candles:96,direction,score:r.score,entry:last.close,entryTime:last.time,createdAt:new Date(last.time).toISOString(),box:r.box.state,flag:r.flag.state,obv:r.obv.trend,divergence:r.obv.divergence,volumeRatio:Math.max(r.box.volumeRatio||0,r.flag.volumeRatio||0),best:0,worst:0,lastPrice:last.close,targets:{}})}stats[market==='CRIPTO'?'crypto':'b3'].ok++}catch(e){stats[market==='CRIPTO'?'crypto':'b3'].error++;console.error(market,symbol,e.message)}}}fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify({generatedAt:new Date().toISOString(),parameters:{interval:'1h',candles:96,minScore:80},stats,signals:signals.slice(0,200)},null,2)+'\n');console.log(`salvos ${signals.length} sinais; cripto ${stats.crypto.ok}/${CRYPTO.length}; B3 ${stats.b3.ok}/${B3.length}`)}
await main();
